[tool.kedro]
package_name = "pipe_deformation"
project_name = "Pipe Deformation"
kedro_init_version = "0.19.10"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/pipe_deformation -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
